ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== README
Dependagen is a tool for dependencies.
Currently only spring boot gradle dependency generation is supported.

=== Features
==== Generation of `spring_boot_dependagen.gradle`
This is interesting when you have e.g. an internal library which shall use same slf4j version as used in
spring boot version.

E.g.

[source]
----
your-spring-boot-application
  +-- spring boot version 2.6.3
     +---- slf4j
  +-- your-lib-v1


your-lib-v1
  -- slf4j

----

How to get them in sync when your-lib-v1 has absolutely no idea about spring.
Of course, you could let gradle do the work for you, but if you want to avoid any side effects, you should
simply use exact sl4fj version in your library as used in spring boot.

===== How to use
[WARNING]
====
This must be done inside *IDE* because currently the spring boot jar does not
contain the template files! This will be changed in future.
====

1. change the spring boot template if necessary (e.g. new spring boot version used, or additional dependencies etc.)
2. Execute `DependaGenApplication.java` with `generate` as parameter.

This will resolve gradle spring boot dependencies found inside 'gradle-templates/spring-boot' and generate

`/gen/gradle-templates/springboot/spring_boot_dependagen.gradle`

You can apply and use the generated data inside your build. 


For example:

[source, groovy]
----
apply from: 'spring_boot_dependagen.gradle'

// ...

dependencies {
   // directly reuse the spring boot dependency
   implementation spring_boot_dependency.slf4j_api
   testImplementation spring_boot_dependency.junit_jupiter
   
   
   // You can use also the library version - maybe for a sub library not already listed,
   // but which must use same version as another spring dependency.
   // (Next is an unnecessary, but working example - because jackson-core dependency is availabl
   // inside spring_boot_dependency with dependagen >=0.2.0)
   implementation "com.fasterxml.jackson.core:jackson-core:${spring_boot_dependency_version.jackson_annotations}"
}
----


